### ISSUE TITLE
Background for events with no image will be filled with images of other events

### ISSUE THREAD

**Issue by sinanxie** [jbuzzi/CampusBuzz_iOS#25]
Background for events with no image will be filled with images of other events in listed circumstances:
a). If user tabs on event filter, sample event (with no image) is not under this filter, and the number of events of this filter is greater than the row number of sample event (without filter), then when user cancels the filter, the background of sample event will be filled with image of other event (be more specific, filled with image of event listed on the same row under previous filter).
b). If user tabs on event filter, and the sample event is under this filter, the background will filled with image of event listed on the same row (under previous filter), but when user cancels the filter, the background go back to nothing (or default), except when case (a) happened, then the background of sample event is always filled with other image if no filter is chosen.
c). Filled with image of the last event after scrolling up and viewing details of other event.

Solution: 
If user doesn't upload a photo, maybe the app will upload a default photo to the Parse? In this case, we might do not need to deal with this kind of problems.

**Comment by jbuzzi** [comment]
Good idea, we'll set a default picture for the event
